//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPx.Catalogs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Regions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Regions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPx.Catalogs.Resources.Regions", typeof(Regions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        internal static string Africa {
            get {
                return ResourceManager.GetString("Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Americas.
        /// </summary>
        internal static string Americas {
            get {
                return ResourceManager.GetString("Americas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antarctica.
        /// </summary>
        internal static string Antarctica {
            get {
                return ResourceManager.GetString("Antarctica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        internal static string Asia {
            get {
                return ResourceManager.GetString("Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia and New Zealand.
        /// </summary>
        internal static string AustraliaNewZealand {
            get {
                return ResourceManager.GetString("AustraliaNewZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caribbean.
        /// </summary>
        internal static string Caribbean {
            get {
                return ResourceManager.GetString("Caribbean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central America.
        /// </summary>
        internal static string CentralAmerica {
            get {
                return ResourceManager.GetString("CentralAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Asia.
        /// </summary>
        internal static string CentralAsia {
            get {
                return ResourceManager.GetString("CentralAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Islands.
        /// </summary>
        internal static string ChannelIslands {
            get {
                return ResourceManager.GetString("ChannelIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Africa.
        /// </summary>
        internal static string EasternAfrica {
            get {
                return ResourceManager.GetString("EasternAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Asia.
        /// </summary>
        internal static string EasternAsia {
            get {
                return ResourceManager.GetString("EasternAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Europe (including Northern Asia).
        /// </summary>
        internal static string EasternEurope {
            get {
                return ResourceManager.GetString("EasternEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        internal static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin America and the Caribbean.
        /// </summary>
        internal static string LatinAmerica {
            get {
                return ResourceManager.GetString("LatinAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melanesia.
        /// </summary>
        internal static string Melanesia {
            get {
                return ResourceManager.GetString("Melanesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micronesia.
        /// </summary>
        internal static string Micronesia {
            get {
                return ResourceManager.GetString("Micronesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Africa.
        /// </summary>
        internal static string MiddleAfrica {
            get {
                return ResourceManager.GetString("MiddleAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        internal static string NorthAmerica {
            get {
                return ResourceManager.GetString("NorthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothern Africa.
        /// </summary>
        internal static string NorthernAfrica {
            get {
                return ResourceManager.GetString("NorthernAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern America.
        /// </summary>
        internal static string NorthernAmerica {
            get {
                return ResourceManager.GetString("NorthernAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Europe.
        /// </summary>
        internal static string NorthernEurope {
            get {
                return ResourceManager.GetString("NorthernEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceania.
        /// </summary>
        internal static string Oceania {
            get {
                return ResourceManager.GetString("Oceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynesia.
        /// </summary>
        internal static string Polynesia {
            get {
                return ResourceManager.GetString("Polynesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South America.
        /// </summary>
        internal static string SouthAmerica {
            get {
                return ResourceManager.GetString("SouthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South-eastern Asia.
        /// </summary>
        internal static string SouthEasternAsia {
            get {
                return ResourceManager.GetString("SouthEasternAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Africa.
        /// </summary>
        internal static string SouthernAfrica {
            get {
                return ResourceManager.GetString("SouthernAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Asia.
        /// </summary>
        internal static string SouthernAsia {
            get {
                return ResourceManager.GetString("SouthernAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Europe.
        /// </summary>
        internal static string SouthernEurope {
            get {
                return ResourceManager.GetString("SouthernEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Saharan Africa.
        /// </summary>
        internal static string SubSaharanAfrica {
            get {
                return ResourceManager.GetString("SubSaharanAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Africa.
        /// </summary>
        internal static string WesternAfrica {
            get {
                return ResourceManager.GetString("WesternAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Asia.
        /// </summary>
        internal static string WesternAsia {
            get {
                return ResourceManager.GetString("WesternAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Europe.
        /// </summary>
        internal static string WesternEurope {
            get {
                return ResourceManager.GetString("WesternEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
